title: Obsidian Unofficial Plugins 
description: An unofficial catalog of Obsidian plugins.  Features plugins that are awaiting acceptance into the official community plugins list.
theme: just-the-docs

url: https://joepetrakovich.github.io/obsidian-unofficial-plugins

aux_links:

nav_enabled: false
color_scheme: dark
