title: Obsidian Unofficial Plugins 
description: An unofficial catalog of Obsidian plugins.  Features plugins that are awaiting acceptance into the official community plugins list.
theme: just-the-docs

url: https://joepetrakovich.github.io/obsidian-unofficial-plugins

github_url: https://github.com

aux_links:

nav_enabled: false
color_scheme: obsidian
heading_anchors: false
search:
  heading_level: 4
callouts:
  warning:
    title: Warning
    color: yellow

ga_tracking: G-TQN74J2E89
